apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: dev01
  labels:
    app: nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        lifecycle:
          preStop:
            sleep:
              seconds: 15
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
      priorityClassName: default-priority
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: dev01
spec:
  type: NodePort
  selector:
    app: nginx2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30020
