apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx4
  namespace: dev01
  labels:
    app: nginx4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx4
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              sleep:
                seconds: 15
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
      priorityClassName: low-priority
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: nginx4
  namespace: dev01
spec:
  type: NodePort
  selector:
    app: nginx4
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040
