apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: nginx1
  name: nginx1
  namespace: dev01
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: nginx2
  name: nginx2
  namespace: dev01
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: nginx3
  name: nginx3
  namespace: dev01
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx3
