apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitrepo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitrepo-app
  template:
    metadata:
      labels:
        app: gitrepo-app
    spec:
      containers:
      - name: app-container
        image: nginx  # Using Nginx as a sample application
        volumeMounts:
        - name: git-repo-volume
          mountPath: /usr/share/nginx/html  # Nginx serves files from this directory

      volumes:
      - name: git-repo-volume
        gitRepo:
          repository: https://github.com/kubernetes/website.git
          revision: master
