---
apiVersion: v1
kind: Namespace
metadata:
  name: dev01
  labels:
    env: dev01         # Environment label
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat01
  labels:
    env: uat01         # Environment label
---
apiVersion: v1
kind: Namespace
metadata:
  name: prd01
  labels:
    env: prd01         # Environment label
