apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "container-resource-policy"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: |
        object.spec.template.spec.containers.all(c, 
          has(c.resources) &&
          has(c.resources.limits) &&
          has(c.resources.limits.cpu)
        )
      message: "container does not have CPU limits set"
    - expression: |
        object.spec.template.spec.containers.all(c, 
          has(c.resources.requests) &&
          has(c.resources.requests.cpu)
        )
      message: "container does not have CPU requests set"
    - expression: |
        object.spec.template.spec.containers.all(c,
          has(c.resources.limits.memory)
        )
      message: "container does not have Memory limits set"
    - expression: |
        object.spec.template.spec.containers.all(c,
          has(c.resources.requests.memory)
        )
      message: "container does not have Memory requests set"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "container-resource-policy-binding"
spec:
  policyName: "container-resource-policy"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: "env"
        operator: In
        values: [dev01, uat01, prd01]
