apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "replicalimit-policy"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= int(params.data['maxReplicas'])"
      messageExpression: "'object.spec.replicas must not be greater than ' + params.data['maxReplicas']"
      reason: Invalid
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: replicalimit-policy-binding
spec:
  policyName: replicalimit-policy
  paramRef:
    name: validation-config
    namespace: default
    parameterNotFoundAction: Allow
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: "env"
        operator: In
        values: [dev01, uat01]