apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s1-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.122.240-192.168.122.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k8s1
  namespace: metallb-system
spec:
  ipAddressPools:
  - k8s1-pool

